### ISSUE TITLE
Create Blender.dockerfile auto-build/test/publish

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#101]
Rationale: right now the test process is very heavy as one needs to build blender with every pull request. This can be optimized (heavily) by splitting off blender compilation (which will not change that often) in its own workflow (sparsely invoked) and having everything else work off pre-built containers.

**Comment by taiya** [comment]
@Qwlouse now these workflow only run when the docker file in the master branch is updated:
– https://github.com/google-research/kubric/blob/main/.github/workflows/blender.yml#L9
– https://github.com/google-research/kubric/blob/main/.github/workflows/kubruntu.yml#L6

And the test run directly from the "lastest" kubruntu image:
https://github.com/google-research/kubric/blob/main/.github/workflows/test.yml

While the lint does not really need an image, and runs in raw python:
https://github.com/google-research/kubric/blob/main/.github/workflows/lint.yml

This means that a pure-python pull request will have a much nicer breakout
of different tests and lint errors, e.g. this [dummy one](https://github.com/google-research/kubric/pull/111) snapshotted below:

![image](https://user-images.githubusercontent.com/4480573/121108776-3235ce00-c7bf-11eb-9781-b013aefd537d.png)

I cannot create a pull request for workflow changes, so I am summarizing them here.

**Comment by Qwlouse** [comment]
> I cannot create a pull request for workflow changes, so ... 

Why not?

> These workflow only run when the docker file in the master branch is updated...

I think you mentioned it in our meeting earlier, but this will lead to using old code for the tests. We can either  
  1. update the `Kubruntu` image on every code-change (which should be fast since the `blender` image can remain fixed)  or
  2. use a dev-container based workflow for the tests

An advantage of going with 1. would be that we automatically will have an up-to-date `Kubruntu` image on dockerhub. A disadvantage is that this becomes weird when running the tests for PRs, because then the `kubruntu` image is updated with non-`main`-branch code. 
The advantage with 2. would be that it is even faster and circumvents the PR problem, but I'm not sure how to set this up in github actions and we'd still have to manually upload Kubruntu images to dockerhub.

**Comment by taiya** [comment]
> Why not?
because in the PR the "stale" actions are executed (sometime preventing you from merging)
perhaps this has changed, but this was the case in the past.

I think I have a (3), where I don't use Kubruntu, but instead use KubruntuDev.
In that case the code used to run tests is the "live" one? No, @Qwlouse ?

**Comment by Qwlouse** [comment]
Wait, KubruntuDev is what I meant by (2). What did you think (2) was?

**Comment by taiya** [comment]
I confirm that once I connected kubruntudev in `test.yml`:
```
jobs:    
  execute:
    runs-on: ubuntu-latest
    container: kubricdockerhub/kubruntudev:latest
```

Then a failed test will show-up in a PR:
![Screen Shot 2021-06-10 at 3 03 47 PM](https://user-images.githubusercontent.com/4480573/121603227-4961ff00-c9fd-11eb-887a-ef17d19be6e0.png)

**Comment by taiya** [comment]
@Qwlouse also added quick container-level test access to makefile:
```
make pytest TEST=test/test_core.py::test_asset_name_readonly
```
