### ISSUE TITLE
The docker crashes without any warning and no output is visible

### ISSUE THREAD

**Issue by kacperkan** [google-research/kubric#172]
I've tried to generate 480 frames of 256x256 images. While the last log was: `INFO:kubric.renderer.blender:Rendered frame '/tmp/tmpjk4_v0qh/images/frame_0480.png' `, there was no output image saved onto drive. `docker ps` showed that stopped functioning entirely. My PC has 6GB and noticed that it was all occupied before the crash.

**Comment by Qwlouse** [comment]
Hey, sorry for the long delay. 
This is very likely a memory issue, since we currently process the entire video at once in memory.
If you want to render large / long videos you might have to change from using `renderer.render()` to manually looping over the frames and calling `renderer.render_still()` for each one, then write the results to disk before moving on to the next one.

**Comment by taiya** [comment]
Kacper, seems I have to re-enable email notifications :)
I guess we got this solved for the CVPR deadline 🎉🎉

**Comment by Wuziyi616** [comment]
I still encounter this problem using the newest Kubric. I was rendering 50 800x800 images and the program got stuck. Changing to `render_still` solve the problem.
