### ISSUE TITLE
The accurate full Id of asset in shapeNet. 

### ISSUE THREAD

**Issue by DelinQu** [google-research/kubric#254]
I create some objects from ShapeNetCore by the following code, but Kubric raises the error that my id is incorrect. 
Although it works well after changing `3dw` to `02958343` according to the exception message, it will crash me if I change my id through exception information. So I wonder is there a more simple way to get the id?

```python
obj = asset_source.create(
    asset_id="3dw.db79ceb1bf94fd81851f021b9ed69c58")
```
- the full id from ShapeNetCore
![image](https://user-images.githubusercontent.com/60593268/177115241-629967cc-186e-478d-9328-f96e34888284.png)
- the exception
```bash
  File "/usr/local/lib/python3.9/dist-packages/kubric/assets/asset_source.py", line 169, in create
    raise KeyError(f"Unknown asset with id='{asset_id}'. Did you mean '{near_match}'?")
KeyError: "Unknown asset with id='3dw.db79ceb1bf94fd81851f021b9ed69c58'. Did you mean '02958343/db79ceb1bf94fd81851f021b9ed69c58'?"
```

**Comment by Qwlouse** [comment]
The part before the slash is the shapenet category id. In this case the one for car (see [here](https://github.com/google-research/kubric/blob/9a868cc735de955709c4c75d9655fff1e90c72e4/shapenet2kubric/shapenet_synsets.py#L259) ). 
This is done because when you download the raw shapenet dataset, it is organized into 55 folders by those category ids. 
Not all synsets in the file linked above are used, but if you go via the [taxonomy viewer](https://shapenet.org/taxonomy-viewer) you can then use the category name on the left to reverse lookup the corresponding id. 
![image](https://user-images.githubusercontent.com/1160920/178019236-a24bbe66-ef7a-49fa-86d3-067c54f06b1e.png)

Alternatively you can just takke the list of all asset-names (`asset_source.all_asset_ids`), split them at the `/` and search through the second half.

**Comment by DelinQu** [comment]
> 

Wow ! thank you so much! :smile:
